Update home.html
BeeStation/Website pull request #4
Opened 2020-04-03 23:06 UTC by mehmetipekpatates

updates outdated stuff and epic wording, probably adds more typos that maintainers should edit out

2020-04-05 15:03 UTC, qwertyquerty commented
You messed up this branch

2020-04-05 15:45 UTC, Crossedfall commented
Since this includes the rule changes, this closes #5 and #6

2020-04-05 15:56 UTC, Crossedfall requested changes
Minor grammar errors introduced, provided some suggestions to improve readability as well.

2020-04-05 15:56 UTC, Crossedfall commented on app/templates/home.html
> +    <p class="text-indent">BeeStation is an Space Station 13 server hosted by Crossedfall that came into being around March 2018.  We brandish ourselves as being a newbie friendly community with LRP
```suggestion
    <p class="text-indent">BeeStation is a Space Station 13 server, hosted by Crossedfall, which was created in March 2018.  We focus on being being a newbie friendly community, with LRP (Golden) and MRP (Sage) servers. Our codebase is built off of /tg/'s foundations, combining our own unique features with those found on other servers.</p>
```

This adds grammatical errors and doesn't read all that well.

2020-04-05 15:56 UTC, Crossedfall commented on app/templates/home.html
> +    <p class="text-indent">Our server is open source, so feel free to contribute to the code! We also have a Discord server with a great helpful community, a forum for ban appeals, staff applications
```suggestion
    <p class="text-indent">Our server is open source, so feel free to contribute to the code! We also have a Discord server with a great helpful community; a forum for ban appeals, staff applications, suggestions and discussions; as well as an informative Wiki.</p>
```

2020-04-05 16:02 UTC, Crossedfall commented on app/templates/home.html
> +    <p class="text-indent">BeeStation is a Space Station 13 server, hosted by Crossedfall, which was created in March 2018.  We focus on being being a newbie friendly community, with LRP (Golden) and
```suggestion
    <p class="text-indent">BeeStation is a Space Station 13 server, hosted by Crossedfall, which was created in March 2018.  We focus on being a newbie friendly community, with LRP (Golden) and MRP (Sage) servers. Our codebase is built off of /tg/'s foundations, combining our own unique features with those found on other servers.</p>
```

I made an oopsie in my corrections. Added an extra `being`. Sorry about that

2020-04-05 16:11 UTC, Crossedfall commented on app/config/rules/bs_golden.json
> +				"Listen to them without argument during the round, but if you feel there is a problem with their actions, report them on the forums afterwards. The Admin Conduct can be found here: https://pasteb
Missed this in my initial review. A pastebin link? Really? Can we not have a forum thread or something?

2020-04-05 16:13 UTC, Crossedfall commented on app/config/rules/bs_golden.json
> +				"Listen to them without argument during the round, but if you feel there is a problem with their actions, report them on the forums afterwards. The Admin Conduct can be found here: https://pasteb
A wiki article that has restricted editing might actually be better

2020-04-06 19:46 UTC, mehmetipekpatates commented
ported bad pastebin to the wiki and changed the link in code

2020-04-09 00:08 UTC, qwertyquerty commented on app/config/rules/bs_golden.json
> +			"title": "Admin Discretion",
You have malformed json here, you're missing an opening curly bracket

2020-04-09 00:08 UTC, qwertyquerty commented on app/config/rules/bs_sage.json
> +		"title": "Admin Discretion",
Please keep consistent indentation

2020-04-12 15:07 UTC, Crossedfall approved these changes

2020-04-14 20:20 UTC, merged